name: "SSH Remote Commands"
description: "Executing remote ssh commands"
author: "Bo-Yi Wu"
inputs:
  host:
    description: "ssh host"
  port:
    description: "ssh port"
    default: 22
  passphrase:
    description: "ssh key passphrase"
  username:
    description: "ssh username"
  password:
    description: "ssh password"
  www_path:
    description: "www_path"
