name: Push
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Exec deploy script with SSH
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: sh ${{ secrets.WWW_PATH }}/androidhub/.deploy/main.sh
      - name: Send dingding notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                  "title": "发布完成",
                  "picUrl": "",
                  "text": "ok",
                  "messageUrl": "https://github.com/sofakeer/androidhub/actions"
              }
            }
